### PR TITLE
Update qtautoupdatergui_fr.ts

### PR DESCRIPTION
**Pull request by SmathiLagui**
correction of translation errors as requested :)

### CODE REVIEW

**Comment by Skycoder42** [comment]
Ah, I think you misunderstood my request. I am working on version 3.0.0 of the library on the major branch. I meant the translations on that branch. However, I have now merged the major branch into the master branch.

Please have a look at the translations, which have been relocated to `src/translations`!

Sorry for the confusion.

**Comment by Skycoder42** [comment]
Thanks for the update. I have merged the major branch into master. Please rebase your commit to the updated master branch. The translations have also been moved to `src/translations` and renamed to be only named `qtautoupdater_<locale>.ts`. Sorry for the inconvenience.

**Comment by SmathiLagui** [comment]
No problem, I will check this file as soon as possible.

**Comment by Skycoder42** [comment]
I copied the file manually myself (See commit 7462d61d0614951d6544c2222c93ca17c555a815), so you don't have to do anything for now. Thanks for your help!

**Pull request closed without merging**
